[package]
name = "prisma-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { features = [
  "migrations",
  # "mutation-callbacks",
], default_features = false, git = "https://github.com/Brendonovich/prisma-client-rust" }